ActivitProzessMonitor.labelActivitiHost.text=Activiti Host:
ActivitProzessMonitor.buttonStartProcess.text=Starten
ActivitProzessMonitor.buttonStopUserTasksThread.actionCommand=stop
ActivitProzessMonitor.buttonStopUserTasksThread.toolTipText=Task-Verarbeitung unterbrechen
