#
# Created by JFormDesigner on Thu Mar 19 17:22:50 CET 2026
#

ActivitProzessMonitor.buttonStartProcess.text=Prozess starten...
ActivitProzessMonitor.buttonStopUserTasksThread.actionCommand=UT-Thread starten...
ActivitProzessMonitor.buttonStopUserTasksThread.toolTipText=UT-Thread starten...
ActivitProzessMonitor.labelActivitiHost.text=Activiti-Host\:
